# Generated by Django 5.0.6 on 2025-12-24 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('farm_size', models.FloatField(help_text='Size in acres')),
                ('contact_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('rice', 'Rice'), ('wheat', 'Wheat'), ('maize', 'Maize'), ('cotton', 'Cotton'), ('sugarcane', 'Sugarcane'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits')], max_length=20)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid')], max_length=20)),
                ('nitrogen', models.FloatField(help_text='N value in mg/kg')),
                ('phosphorus', models.FloatField(help_text='P value in mg/kg')),
                ('potassium', models.FloatField(help_text='K value in mg/kg')),
                ('ph_level', models.FloatField(help_text='pH value')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('humidity', models.FloatField(help_text='Humidity in %')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('soil_moisture', models.FloatField(help_text='Soil moisture in %')),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_type', models.CharField(max_length=50)),
                ('fertilizer_quantity', models.FloatField(help_text='Quantity in kg/acre')),
                ('water_required', models.FloatField(help_text='Water required in liters/day')),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('soil_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farming.soildata')),
            ],
        ),
    ]
